mozillatutorial/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name = 'book-detail'), #use <int:pk> as a stand-in to accept the specific book id
    #<int:pk> will capture an int as a formatted string, then pass it to the view as a parameter named pk (primary key)

]

mozillatutorial/mozillatutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
        path('admin/', admin.site.urls),
        path('catalog/', include('catalog.urls')),
        path('', RedirectView.as_view(url='catalog/')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [path('accounts/', include('django.contrib.auth.urls')),]

mozillatutorial/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


import uuid

# Create your models here

class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    #borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                     '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank = True)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        else:
            return False

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    display_genre.short_description = "Genre"





class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

    def get_absolute_url(self):
        return revese('author-detail', args=[str(self.id)])

mozillatutorial/catalog/views.py
from django.shortcuts import render
from catalog.models import *
from django.views import generic

# Create your views here.

def index(request):
    """view function for home page"""

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_avaliable = BookInstance.objects.filter(status__exact = 'a').count()

    num_authors = Author.objects.count()

#num of visits to this view
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1


    context = {
        'num_books' : num_books,
        'num_instances': num_instances,
        'num_authors': num_authors,
        'num_instances_avaliable':num_instances_avaliable,
        'num_visits': num_visits,
    }
    #return w/ index.html template & defined variables
    return render(request, 'index.html', context=context)

'''
class BookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list' #name for list as template variable
    paginate_by=2
    def get_queryset(self):
        queryset=Book
#queryset = Book.objects.filter(title__icontains="1")[:5] #returns 5 books with '1' in the title
        return queryset
    def get_context_data(self, **kwargs):
#override base implementation
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'just some data'
        return context
'''

class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book

mozillatutorial/catalog/templates/base_generic.html
 
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'books' %}">All books</a></li>
    <li><a href="">All authors</a></li>

  {% if user.is_authenticated %}
    <li>User: {{user.get_username}}</li>
    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}
  </ul>
{% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  
  </div>
</div>

</div>
</body>

</html>

mozillatutorial/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html"}
{% block content%}
    <h1>Title: {{ book.title  }}</h1>

    <p><strong>Author:</strong> <a href="">{{ book.author  }}</a></p> <!-- author detail link not yet defined, update when avaliable-->
    <p><strong>Summary:</strong> {{ book.summary  }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn  }}</p> 
    <p><strong>Language:</strong> {{ book.language  }}</p>  
    <p><strong>Genre:</strong> {{ book.genre.all|join:", "  }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

         {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{%elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{copy.get_status_display}}</p>
            {% if copy.get_status_display%}
                <p><strong>Due to be returned: </strong><{{copy.due_back}}</p>
            {%endif%}
            <p><strong>Imprint:</strong>{{copy.imprint}}</p>
            <p class="text-muted"><strong>Id:</strong>{{copy.id}}</p>
        {%endfor%}
    </div>
{%endblock%}

mozillatutorial/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list%}
    <ul>
        {% for book in book_list%}
        <li>
            <a href="{{ book.get_absolute_url }}">{{book.title}}</a> ({{book.author}})
        </li>
        {%endfor%}
    </ul>
    {%else %}
        <p>There are no books in the library</p>
    {%endif%}

{%endblock%}

mozillatutorial/catalog/templates/index.html
{% extends "base_generic.html"%}

{% block content %}

<h1>Local Library Home</h1>
<p>Welcome to Local Library, a website created by <em> Brian Chen with the Mozilla Django tutorial</em>!</p> 
<h2>dynamic content</h2>
<p>this library has the following record counts:</p>
<ul>
    
<!--
    Under dynamic content, put variables in { {   }} (ignore that space) double curvy brackets
    Note that this should be the same as the variables here are the *KEYS* 
    passed in the context dictionary of the view: the view takes the *VALUE* variable from 
    the model
-->
    <li><strong>Books: </strong>{{num_books}}</li>
    <li><strong>Total Copies: </strong>{{num_instances}}</li>
    <li><strong>Copies avaliable: </strong>{{num_instances_avaliable}}</li>
    <li><strong>Authors: </strong>{{num_authors}}</li>
</ul>

<p> You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>


{% endblock %}